# Travis CI Configuration file
# @link https://travis-ci.org/

# Using shell for the project
language: shell

script:
  # Validates the included scripts
  - find . -type f -name "*.sh" | xargs shellcheck
