# Travis CI Configuration file
# @link https://travis-ci.org/

env:
  - DEPLOY=true

# ShellCheck is installed
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
  # Validates the included scripts
  - shellcheck java/maven/create-maven-settings.sh
  - shellcheck java/maven/deploy-site.sh
  - shellcheck java/maven/deploy.sh
  - shellcheck travis/load-travis-environment.sh
  - shellcheck bintray/deploy_debian.sh
  # Creates the package
  - dpkg-buildpackage -rfakeroot -us -uc
after_success:
  - chmod +x ./bintray/deploy_debian.sh
  - chmod +x ./travis/load-travis-environment.sh
  # Prepares CI environment
  - source ./travis/load-travis-environment.sh
  # Deploys
  - ./bintray/deploy_debian.sh $DO_DEPLOY ../wandrell-ci-scripts_0.1.0_all.deb https://api.bintray.com/content/bernardo-mg/Debian/ci-shell-scripts/0.1.0/wandrell-ci-scripts_0.1.0_all.deb