# Travis CI Configuration file
# @link https://travis-ci.org/

env:
  - DEPLOY=true

# ShellCheck is installed
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
  # Validates the included scripts
  - find . -type f -name "*.sh" | xargs shellcheck
  # Creates the package
  - dpkg-buildpackage -rfakeroot -us -uc
after_success:
  - chmod +x ./bintray/deploy_debian.sh
  - chmod +x ./travis/load-travis-environment.sh
  # Prepares CI environment
  - source ./travis/load-travis-environment.sh
  # Deploys
  - ./bintray/deploy_debian.sh $DO_DEPLOY ci-shell-scripts 0.1.0 all https://api.bintray.com/content/bernardo-mg/Debian/